# Generated by Django 5.2.7 on 2026-06-04 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0002_alter_payment_options_alter_payment_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='hotel_booking.booking', verbose_name='Бронирование'),
        ),
    ]
