# Generated by Django 5.2.7 on 2026-05-28 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0002_alter_booking_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['user__username'], 'verbose_name': 'Гость', 'verbose_name_plural': 'Гости'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['hotel__name', 'room_number'], 'verbose_name': 'Номер', 'verbose_name_plural': 'Номера'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
    ]
