# Generated by Django 5.2.7 on 2026-05-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0003_alter_guest_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='room',
            name='square',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Площадь (кв.м)'),
        ),
    ]
