# Generated by Django 5.2.7 on 2026-06-01 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0005_guest_avatar_alter_guest_phone_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('manager', 'Менеджер отеля'), ('admin', 'Администратор')], default='guest', max_length=20, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='hotel_booking.guest', verbose_name='Гость')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='Дата заезда')),
                ('check_out_date', models.DateField(verbose_name='Дата выезда')),
                ('guests_count', models.IntegerField(default=2, verbose_name='Количество гостей')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hotel_booking.cart', verbose_name='Корзина')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='hotel_booking.room', verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Позиция корзины',
                'verbose_name_plural': 'Позиции корзины',
                'unique_together': {('cart', 'room', 'check_in_date', 'check_out_date')},
            },
        ),
    ]
