# Generated by Django 5.2.7 on 2026-06-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_booking', '0006_guest_role_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='managed_hotels',
            field=models.ManyToManyField(blank=True, related_name='managers', to='hotel_booking.hotel', verbose_name='Управляемые отели'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='role',
            field=models.CharField(choices=[('guest', 'Гость'), ('manager', 'Менеджер отеля'), ('admin', 'Администратор')], default='guest', max_length=20),
        ),
    ]
